// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC142_gS6BA7leHbCGVoByFmkluYBVuYZg',
    appId: '1:122921125037:web:97bbcdf46c3afd11f33224',
    messagingSenderId: '122921125037',
    projectId: 'flutter-travel-review',
    authDomain: 'flutter-travel-review.firebaseapp.com',
    storageBucket: 'flutter-travel-review.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtBX6e2vBZ8R1dsKxxqxyZoNwYbqNHsAs',
    appId: '1:122921125037:android:f2dcb7c2f81b39c7f33224',
    messagingSenderId: '122921125037',
    projectId: 'flutter-travel-review',
    storageBucket: 'flutter-travel-review.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM29MWb6qrRWAq0yptTtjeNJfOJuv-rus',
    appId: '1:122921125037:ios:cafceb84d10a2fe6f33224',
    messagingSenderId: '122921125037',
    projectId: 'flutter-travel-review',
    storageBucket: 'flutter-travel-review.firebasestorage.app',
    androidClientId: '122921125037-ue00pt8jf0jao5557e81v6ij722uv80k.apps.googleusercontent.com',
    iosClientId: '122921125037-c4b57u6jaij8kocpdmtqe0ciaq08rc3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTravelsApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM29MWb6qrRWAq0yptTtjeNJfOJuv-rus',
    appId: '1:122921125037:ios:cafceb84d10a2fe6f33224',
    messagingSenderId: '122921125037',
    projectId: 'flutter-travel-review',
    storageBucket: 'flutter-travel-review.firebasestorage.app',
    androidClientId: '122921125037-ue00pt8jf0jao5557e81v6ij722uv80k.apps.googleusercontent.com',
    iosClientId: '122921125037-c4b57u6jaij8kocpdmtqe0ciaq08rc3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTravelsApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC142_gS6BA7leHbCGVoByFmkluYBVuYZg',
    appId: '1:122921125037:web:60207c16c1425602f33224',
    messagingSenderId: '122921125037',
    projectId: 'flutter-travel-review',
    authDomain: 'flutter-travel-review.firebaseapp.com',
    storageBucket: 'flutter-travel-review.firebasestorage.app',
  );

}
